# Generated by Django 6.0.5 on 2026-06-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='business',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PRO', 'Professional'), ('SPONSORED', 'Sponsored (Top Tier)')], db_index=True, default='BASIC', max_length=20),
        ),
    ]
