# Generated by Django 6.0.5 on 2026-06-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='Used for URLs. Auto-generated if left blank.', max_length=150, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to hide/show this category globally.', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this category on the homepage.', verbose_name='Featured')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='Sort Order')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title. Defaults to category name if blank.', max_length=150, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO description for search engines.', max_length=255, verbose_name='Meta Description')),
                ('parent', models.ForeignKey(blank=True, help_text='Select a parent category to make this a sub-category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx'), models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['is_active', 'is_featured'], name='categories__is_acti_0cda94_idx'), models.Index(fields=['parent'], name='categories__parent__91c7d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_category_per_parent')],
            },
        ),
    ]
