# Generated by Django 6.0.5 on 2026-06-10 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a scalable vector graphic (SVG) or WebP for optimal PWA performance.', null=True, upload_to='category_images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Icon'),
        ),
    ]
