# Generated by Django 6.0.5 on 2026-06-10 10:30

import django.core.validators
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a scalable vector graphic (SVG) or WebP for optimal PWA performance.', null=True, storage=storages.backends.s3.S3Storage(), upload_to='category_images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg', 'jpeg', 'webp'])], verbose_name='Icon'),
        ),
    ]
